mutation CaptureEmail($email: String!) {
  captureEmail(email: $email) {
    id
    email
  }
}

mutation Invite($emails: [String], $groups: [String], $role: String) {
  invite(emails: $emails, groups: $groups, role: $role) {
    ...UserFields
  }
}

mutation Signup(
  $id: String!
  $firstname: String!
  $lastname: String!
  $password: String!
) {
  signup(
    id: $id
    firstname: $firstname
    lastname: $lastname
    password: $password
  ) {
    token
    user {
      id
      email
    }
  }
}


mutation Login($email: String!, $password: String!) {
  login(email: $email, password: $password) {
    token
    user {
      id
      email
    }
  }
}

mutation UpdateUser($id: String!, $input: UserInput) {
  updateUser(id: $id, input: $input) {
    ...UserFields
  }
}


fragment FolderFields on Folder {
  id
  name
  parent
  description
  shareWith
}

fragment UserFields on User {
  id
  name
  firstname
  lastname
  email
  jobTitle
  avatarColor
  role
  status
  createdAt
}

fragment GroupFields on Group {
  id
  team
  name
  initials
  avatarColor
  users
}

query GetFolders($parent: String) {
  getFolders(parent: $parent) {
    ...FolderFields
  }
}

query GetFolder($id: String!) {
  getFolder(id: $id) {
    ...FolderFields
  }
}

query GetTeam {
  getTeam {
    id
    name
  }
}

mutation CreateFolder($parent: String, $name: String!) {
  createFolder(parent: $parent, name: $name) {
    ...FolderFields
  }
}

mutation UpdateFolder($id: String!, $input: FolderInput) {
  updateFolder(id: $id, input: $input) {
    ...FolderFields
  }
}

mutation DeleteFolder($id: String!) {
  deleteFolder(id: $id)
}

query GetUsers {
  getUsers {
    ...UserFields
  }
}

query GetUser($id: String) {
  getUser(id: $id) { ...UserFields }
}

query GetGroups {
  getGroups {
    ...GroupFields
  }
}
